#!/usr/bin/env python3
# Chatwoot admin/account/token provisioner for the Secretária V4 onboarding (test/headless shortcut; in
# the real product the operator creates the first admin in the browser). Runs a Rails runner script INSIDE
# the Chatwoot container over SSH, base64-piped so the account name (accents/spaces) and the script's own
# quotes never hit a shell. Idempotent: find_or_create for account / user / access-token.
#
# Output: the admin api_access_token (+ a password GENERATED in-container for fresh users) is written to a
# 0600 file; only metadata is printed. The token is what v4 deployment_connect + the Inbox API need. The
# password is generated by SecureRandom in-container and never passed in, so no secret transits argv/env.
# Works on any tier (the admin token is minted the same way behind Coolify, Portainer or plain compose).
# Python 3 stdlib only (no pip). Network/SSH runs via Bash with dangerouslyDisableSandbox:true (00-prereqs).
import argparse
import base64
import json
import re
import shlex
import subprocess
import sys
from pathlib import Path

CONTAINER_RE = re.compile(r"^[A-Za-z0-9_.-]+$")

# Non-secret inputs (name/email) arrive base64-decoded in-container so accents/spaces can't break quoting.
# The password is minted by SecureRandom; role 1 = administrator. RESULT_JSON: marks the line we parse.
RUBY_PROVISION = r'''
require 'base64'; require 'securerandom'; require 'json'
name = Base64.strict_decode64("__B64_NAME__").force_encoding("UTF-8")
email = Base64.strict_decode64("__B64_EMAIL__").force_encoding("UTF-8")
acc = Account.find_or_create_by!(name: name)
u = User.find_or_initialize_by(email: email)
fresh = u.new_record?
pw = nil
if fresh
  pw = SecureRandom.urlsafe_base64(18)
  u.password = pw
  u.password_confirmation = pw
  u.name = "Admin"
end
u.confirmed_at ||= Time.current
u.save!
AccountUser.find_or_create_by!(account_id: acc.id, user_id: u.id).update!(role: 1)
at = u.access_token || u.create_access_token
puts "RESULT_JSON:" + JSON.generate({"account_id" => acc.id, "user_id" => u.id, "email" => email, "token" => at.token, "password" => pw, "created" => fresh})
'''

# Re-runs the fazer.ai "check new versions" job so the hub-side subscription (Kanban/Pro) registers, then
# reports the subscription config key NAMES present (+ any *status* values); never dumps raw config values,
# which could hold a secret. jitter_applied:true is mandatory (else the job only reschedules, no sync).
RUBY_REFRESH = r'''
require 'json'
Internal::CheckNewVersionsJob.perform_now(jitter_applied: true)
names = InstallationConfig.where("name ILIKE '%subscription%' OR name ILIKE 'fazer%'").pluck(:name)
diag = {}
%w[FAZER_AI_SUBSCRIPTION_SYNC_ERROR_MESSAGE FAZER_AI_SUBSCRIPTION_VERIFIED_AT].each { |k| diag[k] = InstallationConfig.find_by(name: k)&.value }
puts "RESULT_JSON:" + JSON.generate({"refreshed" => true, "config_keys" => names, "diagnostics" => diag})
'''


def out(obj, code=0):
    print(json.dumps(obj))
    sys.exit(code)


def fail(msg, **extra):
    out({"ok": False, "error": msg, **extra}, code=1)


def b64_pipe(payload, target):
    blob = base64.b64encode(payload.encode("utf-8")).decode("ascii")
    return f"echo '{blob}' | base64 -d | {target}"


def run_ssh(dest, ssh_opts, remote_cmd, timeout):
    extra = shlex.split(ssh_opts) if ssh_opts else []
    argv = ["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=15", *extra, dest, remote_cmd]
    try:
        return subprocess.run(argv, capture_output=True, text=True, timeout=timeout)
    except FileNotFoundError:
        fail("ssh not found on PATH")
    except subprocess.TimeoutExpired:
        fail(f"ssh timed out after {timeout}s", dest=dest)


def cmd_provision(args):
    if not CONTAINER_RE.match(args.container):
        fail(f"invalid --container {args.container!r} (expected [A-Za-z0-9_.-]+)")
    if "@" not in args.email:
        fail("--email must be an email address")
    ruby = RUBY_PROVISION.replace(
        "__B64_NAME__", base64.b64encode(args.account_name.encode("utf-8")).decode("ascii")
    ).replace("__B64_EMAIL__", base64.b64encode(args.email.encode("utf-8")).decode("ascii"))
    target = f"docker exec -i {args.container} bundle exec rails runner -"
    proc = run_ssh(args.ssh, args.ssh_opts, b64_pipe(ruby, target), args.timeout)
    combined = (proc.stdout or "") + "\n" + (proc.stderr or "")
    match = re.search(r"RESULT_JSON:(\{.*\})", combined)
    if not match:
        fail(
            "Rails runner returned no result (is --container the Chatwoot rails container?)",
            exit_code=proc.returncode,
            stdout=(proc.stdout or "")[-600:],
            stderr=(proc.stderr or "")[-600:],
        )
    try:
        data = json.loads(match.group(1))
    except ValueError:
        fail("could not parse RESULT_JSON", raw=match.group(1)[:200])
    dest = Path(args.out)
    dest.write_text(
        json.dumps(
            {
                "account_id": data["account_id"],
                "user_id": data["user_id"],
                "email": data["email"],
                "api_access_token": data["token"],
                "password": data.get("password"),
                "created": data.get("created"),
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    try:
        dest.chmod(0o600)
    except OSError:
        pass
    minted = " + generated password" if data.get("password") else ""
    out(
        {
            "ok": True,
            "out_file": str(dest),
            "account_id": data["account_id"],
            "user_id": data["user_id"],
            "email": data["email"],
            "created": data.get("created"),
            "note": f"api_access_token{minted} written to file (chmod 600), not printed",
        }
    )


def cmd_refresh_subscription(args):
    if not CONTAINER_RE.match(args.container):
        fail(f"invalid --container {args.container!r} (expected [A-Za-z0-9_.-]+)")
    target = f"docker exec -i {args.container} bundle exec rails runner -"
    proc = run_ssh(args.ssh, args.ssh_opts, b64_pipe(RUBY_REFRESH, target), args.timeout)
    combined = (proc.stdout or "") + "\n" + (proc.stderr or "")
    match = re.search(r"RESULT_JSON:(\{.*\})", combined)
    if not match:
        fail(
            "Rails runner returned no result (is --container the Chatwoot rails container?)",
            exit_code=proc.returncode,
            stdout=(proc.stdout or "")[-600:],
            stderr=(proc.stderr or "")[-600:],
        )
    try:
        data = json.loads(match.group(1))
    except ValueError:
        fail("could not parse RESULT_JSON", raw=match.group(1)[:200])
    out({"ok": True, **data})


def build_parser():
    parser = argparse.ArgumentParser(
        prog="chatwoot-admin.py",
        description="Chatwoot admin/account/token + subscription refresh via a Rails runner over SSH.",
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    ssh = argparse.ArgumentParser(add_help=False)
    ssh.add_argument("--ssh", required=True, metavar="USER@HOST", help="SSH destination, e.g. root@1.2.3.4")
    ssh.add_argument("--container", required=True, help="Chatwoot rails container (from docker ps)")
    ssh.add_argument("--ssh-opts", default="", help="extra ssh options, e.g. '-i ~/.ssh/key -p 2222'")
    ssh.add_argument("--timeout", type=int, default=180)

    prov = sub.add_parser("provision", parents=[ssh], help="find_or_create account + admin user + token (idempotent)")
    prov.add_argument("--account-name", required=True, help="display name, e.g. 'Clínica Moreira'")
    prov.add_argument("--email", required=True, help="admin email")
    prov.add_argument("--out", required=True, help="file to write the token + password to (chmod 600)")
    prov.set_defaults(fn=cmd_provision)

    refresh = sub.add_parser(
        "refresh-subscription", parents=[ssh], help="run the fazer.ai Refresh job + report subscription config"
    )
    refresh.set_defaults(fn=cmd_refresh_subscription)

    return parser


def main():
    args = build_parser().parse_args()
    args.fn(args)


if __name__ == "__main__":
    main()
